### ISSUE TITLE
nextjs-oauth example missing many of the example files

### ISSUE THREAD

**Issue by durw4rd** [miroapp/app-examples#171]
Hi, I like the idea behind the nextjs-oauth app example but at the moment, the repository is missing much of the content that's shown in the Readme file. The `Components` folder is missing completely as well as all `Pages` that are not responsible for the authentication. The `constants.js` file is also missing.

All of the above makes the example a lot less helpful.

**Comment by horeaporutiu** [comment]
Hi @durw4rd - sorry for the late response here. I've added notifications for these issues so  our team will be notified in a timely manner. 

I've just checked the `nextjs-oauth` app and I see there is a `sample.env` file which should take the place of `constants.js` file. Also I see that the `pages/api` folder has `signin`, `redirect` and `authenticate` files. I believe that should be enough but please let me know if you think something is missing. I've tried the app recently and I do think it is working fine. Let me know if you find otherwise. Thank you for opening this issue!
