### ISSUE TITLE
CSRF token is not valid

### ISSUE THREAD

**Issue by nathanbowang** [miroapp/app-examples#206]
Hi, when I click the APP icon in the board, it show me a login button. After select the developer team and click Add again, I got this error: CSRF token is not valid
![image](https://github.com/miroapp/app-examples/assets/30286194/be0eba38-ac4d-476b-9d32-a6071db1c084)

**Comment by horeaporutiu** [comment]
Hi @natebowang 

Sorry I missed this. I have put an automation in place to be notified of new issues on this repo, so should be able to respond much quicker now. 

Were you seeing this error from one of the app-examples? or which app were you running when you saw this error? Any other details you can provide would be super helpful:

- was it using webSDK + REST API? Or only one or the other?

You can also try to clear the miro cookies and that sometimes will help the issue. For example I have a screenshot below which shows clearing the cookies from Chrome -> View -> Developer -> Developer Tools -> Application -> Storage -> Cookies -> https://miro.com -> Clear

Please let me know if that solved the issue! 

![Screenshot 2023-12-07 at 13 41 07](https://github.com/miroapp/app-examples/assets/10428517/60ee6069-dc7d-4366-bba4-966a28229978)

**Comment by dncrews** [comment]
I'm not OP, but I came across this thread because I:

1. Ran `npx create-miro-app@latest`
2. Installed my app in my developer team
3. Loaded the app in Miro
4. Clicked on the "Login" button in the app in Miro

However, if instead I manually go to `locahost:3000`, and click the "Login" button there, the login flow works. I can then reload the app in Miro, and it will work (already logged in).

**Comment by horeaporutiu** [comment]
Thanks for sharing your particular solution @dncrews! Which particular video are you referring to which is not matching? Want to make sure I can take a look and update it if need be.

**Comment by mrobert09** [comment]
I am neither of the above two people but I can confirm I'm getting the same issue as they are. I followed the exact same steps as dncrews and I get the CSRF token is not valid error when attempting to go through the miro app on the miro website. However if I directly got to localhost:3000 the API works as expected.

**Comment by janza** [comment]
Hi all, this should be fixed in the latest version of `create-miro-app` (v1.15.3).

For existing apps created from the template this can be fixed by updating the Login button in `src/app/page.tsx` with `target="_blank"` attribute so that the login screen opens in a new tab:

```
<a className="button button-primary" href={authUrl} target="_blank">
  Login
</a>
```
Let me know if you still see these issues after applying the fix or with the new version of create-miro-app.

**Comment by nathanbowang** [comment]
Thanks!
