### ISSUE TITLE
Where can I find the addisonschultz/github-cards repo

### ISSUE THREAD

**Issue by natebowang** [miroapp/app-examples#207]
In [this video](https://www.youtube.com/watch?v=Ml_ZoWaKAV4) there is a demo of 2-way sync and GH sync. But the original repo does not exist now. Can I find it somewhere else?

**Comment by horeaporutiu** [comment]
Hi @natebowang sorry for the late response here.

The closest thing we have currently is this one: https://github.com/bishopwm/github-cards

Unfortunately, since GitHub has deprecated ("classic") projects, and the intergration was built to work with "classic, now deprecated" projects, it will be tough to work with the example app unless you have some "classic" projects in your own GitHub repo. 

Sorry for the inconvenience here. Please let me know if you have any further questions.
